### ISSUE TITLE
Where is GSA-PIV-Signer-vX.x.x ZIP?

### ISSUE THREAD

**Issue by djernst** [GSA/gsa-icam-card-builder#19]
#### Description of Issue: ####
The Readme's "Getting Started/Extracting the tools" section states that there is a "GSA-PIV-Signer-vX.x.x.zip" archive. 

#### Details of Issue: ####
Where do you get this file?  It does not seem to exist in the repo.

**Comment by bob-fontana** [comment]
If you need the zip file really quick, you can go to the Releases and pull the latest, which is 1.8.74.  It *does not* include the latest revisions from last night.

**Comment by bob-fontana** [comment]
Fixed by commit d2b2453.  That's not to say that this entire README.md needs updating.

**Comment by djernst** [comment]
Thank you!  I'm still a newbie with GitHub.  It's painfully obvious now!
:-)

Dan

**Comment by djernst** [comment]
It works!  I needed to run as sudo otherwise it could not talk to the readers.  I was not expecting that as the other utilities (opensc) do not need to run as sudo.

**Comment by djernst** [comment]
I have a general question.  I need to acquire smartcards.  Where can get them for use with this system? What are the minimum requirements for the card?  Will any ISO7816 card work?

**Comment by bob-fontana** [comment]
> 
> 
> I have a general question. I need to acquire smartcards. Where can get them for use with this system? What are the minimum requirements for the card? Will any ISO7816 card work?

You can acquire pre-written cards that contain the exact data you see in this repo from CertiPath at https://www.certipath.com/store/.  Once we've completed the encoding piece (under construction), you will be able to personalize the cards further using these utilities.  However, not any smart card will work.  It must have the PIV applet on it, and you will need the master keys to the card in order to unlock it for writing.  Assuming that we complete the encoder, you'll be able purchase PIV cards from IDEMIA (Oberthur), Gemalto, G&D, and HID.  The GSA Approved Products list contains the list of [PIV card industry partners](https://www.idmanagement.gov/approved-products-list-piv/).

**Comment by djernst** [comment]
Ok.  I was suspecting that this would be the case.  I do have the set of
NIST Test Cards (of which I currently locked out 2 of them trying to run
the Test Runner app).  Hypothetically, would I be able to use one of them
if I new the master keys and rewrite it?
